### ISSUE TITLE
Release IsoMemo Data package on CRAN #1

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/isomemo-data#1]
Original Ticket: https://github.com/INWT/mpi-iso-app-data/issues/1

Ricardo asked us to publish the package to load the data to CRAN.

The code is basically ready, you can run the getData package from the package in this repository. There are two things remaining:

- Write examples how to use the `getData` functionality as part of the Roxygen documentation
- Publish R package using `devtools::release()` This will ask you (a lot of) questions and finally upload the package

he Rproj file works, let me know if you have any advise on my next steps:

- [x] Verify with Ricardo this is the outcome he wants with the single getData() function
- [x] write documentation for Roxygen like [here](https://cran.r-project.org/web/packages/roxygen2/vignettes/roxygen2.html)
- [x] Publish R package using devtools::release() This will ask you (a lot of) questions and finally upload the package, documentation here: https://r-pkgs.org/release.html and https://r-pkgs.org/release.html#release-process
- [x] CHECKS: https://stackoverflow.com/questions/20021791/cran-package-check-finds-warning-that-r-cmd-check-as-cran-doesnt

I am already starting the documentation process for Roxygen, and follow these instructions here: https://www.mzes.uni-mannheim.de/socialsciencedatalab/article/r-package/
- video tutorial: https://www.youtube.com/watch?v=EpTkT6Rkgbs
- more tutorial: CRAN & PYPI

**Comment by jroachell15** [comment]
@wahani all the warnings and errors are fixed now but... 

I have a question on this NOTE:
*** checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .dockerignore**

What should I do with this? should I just delete the dockerignore file? 
see full log:
```
* using log directory ‘/nethome/jroachell/Git-Repos/MPI_2022/IsomemoData.Rcheck’
* using R version 4.1.2 (2021-11-01)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘IsomemoData/DESCRIPTION’ ... OK
* this is package ‘IsomemoData’ version ‘1.0.0’
* package encoding: UTF-8
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... NOTE
Found the following hidden files and directories:
  .dockerignore
These were most likely included in error. See section ‘Package
structure’ in the ‘Writing R Extensions’ manual.
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘IsomemoData’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking ‘build’ directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking installed files from ‘inst/doc’ ... OK
* checking files in ‘vignettes’ ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... OK
  Running ‘testthat.R’
* checking for unstated dependencies in vignettes ... OK
* checking package vignettes in ‘inst/doc’ ... OK
* checking running R code from vignettes ... NONE
  ‘Using-IsoMemo-API.Rmd’ using ‘UTF-8’... OK
* checking re-building of vignette outputs ... OK
* checking PDF version of manual ... OK
* DONE
Status: 1 NOTE
```

**Comment by wahani** [comment]
I added a line to the .Rbuildignore. Should be gone now.

I still see an error on Jenkins: https://isomemodb.com/jenkins/job/Pandora-IsoMemo/job/isomemo-data/job/main/8/console

**Comment by jroachell15** [comment]
@wahani I have also run a `devtools::build_site()` and rendered a package webpage for this package, where can we host this?
https://github.com/Pandora-IsoMemo/isomemo-data/tree/main/docs

![image](https://user-images.githubusercontent.com/73887426/163786665-ce5e0117-7b0f-4217-bab3-4e8d6001ee6a.png)

**Comment by jroachell15** [comment]
@wahani 

I ran: `devtools::check_rhub()`

`> checking CRAN incoming feasibility ... NOTE
  Maintainer: 'Jianyin Roachell <jianyin.roachell@inwt-statistics.de>'
  
  New submission
  
  Possibly misspelled words in DESCRIPTION:
    IsoMemo (2:62, 10:76)

> checking dependencies in R code ... NOTE
  Namespace in Imports field not imported from: 'curl'
    All declared Imports should be used.

> checking examples ... NOTE
  Examples with CPU (user + system) or elapsed time > 5s
          user system elapsed
  getData 1.22   0.58    6.81

> checking for detritus in the temp directory ... NOTE
  Found the following files/directories:
    'lastMiKTeXException'

0 errors ✓ | 0 warnings ✓ | 4 notes x`
![image](https://user-images.githubusercontent.com/73887426/163803347-f9e86366-81c6-4177-b027-8a0f6509755a.png)


I see that on Jenkins: all the test passed:
![image](https://user-images.githubusercontent.com/73887426/163804152-8be3dbe7-d0cb-4aeb-bbc2-d573c073ef2e.png)



Could you please advise me what to do next? I have done some stacksoverflow that some of these notes can be ignored and just release the package. I have tried all i can to rid of these notes, but these aren't errors or warnings, so is it okay for me to publish to CRAN? 

please advise,

Jian

**Comment by wahani** [comment]
> where can we host this?

https://pandora-isomemo.github.io/isomemo-data/

![grafik](https://user-images.githubusercontent.com/3105646/164181487-e9336720-c1dc-4ced-b914-e0817ebb86af.png)

- I don't see where curl is used. Do you need that dependency?
- You may remove the following line https://github.com/Pandora-IsoMemo/isomemo-data/blob/92f85c07faa98e1517a550c5ef8010b4c0064444/R/00-Namespace.R#L2 since the `module` functions is called with a fully qualified name. Maybe that resolves this.

![grafik](https://user-images.githubusercontent.com/3105646/164181829-978db77d-2a16-450b-9a1e-49c6b20c7561.png)

- Please add the docs folder to the .Rbuildignore file

Please try these changes and check again on rhub.

**Comment by jroachell15** [comment]
@wahani 

I run the Windows Dev testing, all seems to pass. results are here: 


`Dear package maintainer,

this notification has been generated automatically.
Your package IsoMemo_1.0.5.tar.gz has been built (if working) and checked for Windows.
Please check the log files and (if working) the binary package at:
https://win-builder.r-project.org/vwd5qKL583y8
The files will be removed after roughly 72 hours.
Installation time in seconds: 5
Check time in seconds: 96
Status: 1 NOTE
R Under development (unstable) (2022-04-27 r82266 ucrt)

All the best,
Uwe Ligges
(CRAN maintainer of binary packages for Windows)`


let me know if you see something fishy, if not, I will officially release on CRAN this package

**Comment by jroachell15** [comment]
@wahani 

I am going through the rest of the checks on `devtools::release()`, and there is one question I don't know. 

![image](https://user-images.githubusercontent.com/73887426/165724744-20e0b8af-dbe8-4f5f-96ef-b893f77c0382.png)


It's regarding the docs folder with the online hosting of the documentation? What am I suppose to do here?

**Comment by wahani** [comment]
> It's regarding the docs folder with the online hosting of the documentation? What am I suppose to do here?

If the folder is up to date, you can answer with 'yes'. devtools is just going through some general topics you may have forgotten. The content in ./docs is indeed the version we see on https://pandora-isomemo.github.io/isomemo-data/

**Comment by jroachell15** [comment]
R PACKAGE has been submitted to CRAN
